[telegram]
api_id = ""
api_hash = ""
phone_numbers = ["+19373833"]
password = ""

[settings]
joiner = false
forward_message = false
forward_message_id = ""
forward_from_group = ""
send_custom_message = true
custom_msg_text = "hello"
delay = 0
cycle_delay = 60
skip_msg = true

[logging]
discord_logging = true 
webhook_url = ""

[show_settings]
print_settings = true
webhook_settings = true